# Generated by Django 4.0.3 on 2022-05-28 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_project_enlace_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='enlace',
            new_name='link',
        ),
    ]
